/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package payroll_app;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void testAddSalariedEmployee() {
    	int empld = 1;
    	AddSalariedEmployee t(empld, "Bob", "Home", 1000.00);
    	t.xecute();
    	Employee* e = GpayrollDatabase.GetEmployee(empld);
    	
    	assertEquals("Bob", e.getName());
    	
    	PaymentClassification pc = e.GetClassification();
    	// SalariedClassification sc = dynamic_cast<SalariedClassification*>(pc);
    	// assert(sc);
    	assertEquals(1000.00, sc.GetSalary(), .001);
    	
    	PaymentSchedule ps = e.GetSchedule();
    	// MonthlySchedule ms = dynamic_cast<MonthlySchedule*>(ps);
    	// assert (ms) ;
    	
    	PaymentMethod pm = e.GetMethod();
    	// HoldMethod* hm = dynamic_cast<HoldMethod*>(pm);
    	// assert (hm) ; 
    }
}
